### ISSUE TITLE
systemd-resolved fails to start

### ISSUE THREAD

**Issue by pmbarrett314** [random-archer/mkinitcpio-systemd-tool#1]
I'm currently trying to use this hook as mentioned in the wiki to get remote unlocking of my root drive. I added the appropriate hooks, and I've been running into issues with `systemd-resolved.service`. `journalctl` from the debug shell shows that the service is outputting the error `Failed to run 'start' task: No such file or directory`, and that it `Failed with result 'resources'`. It tries to start repeatedly with the same result.

I've done quite a bit of digging, but my understanding of systemd and the initramfs is still pretty superficial, so I probably just don't know where to look.

I have also just now realized that this particular service doesn't seem to be necessary for what I'm trying to do, however, it would be nice not to have the error showing up, so any insight you could provide would be helpful.

**Comment by Andrei-Pozolotin** [comment]
1) thanks for the report
2) yes, known issue since v232
3) should be gone with release of v233
https://github.com/systemd/systemd/milestone/10

**Comment by francoism90** [comment]
Hmm, I'm running v233 but still seeing this message.

**Comment by pmbarrett314** [comment]
I am still seeing the error as well. But I don't have to use a workaround to get other things to work any more, so that's something.

**Comment by Andrei-Pozolotin** [comment]
fixed by:
https://github.com/random-archer/mkinitcpio-systemd-tool/commit/d443348f60a2810672f5e55887195a3d140d8a5e

see details:
https://github.com/systemd/systemd/issues/5610
