### ISSUE TITLE
initrd-shell should not use /root/.ssh/authorized_keys

### ISSUE THREAD

**Issue by kescherCode** [random-archer/mkinitcpio-systemd-tool#103]
The list of devices that are supposed to be able to unlock a system is not neccessarily overlapping with the list of keys that should allowed to access the normal root user.

Proposal: Take the file from `/etc/mkinitcpio-systemd-tool/config/authorized_keys` instead.

**Comment by ArchangeGabriel** [comment]
(OTOH, no key should allow access to the normal root user — but I’m fine with a dedicated setting)
