### ISSUE TITLE
It's not clear what to do if '/etc/initrd-release' is non-existent

### ISSUE THREAD

**Issue by ShapeShifter499** [random-archer/mkinitcpio-systemd-tool#13]
Is '/etc/initrd-release'  required?    I'm trying to set this up on a Raspberry Pi so I can remotely decrypt my file systems.  It seems like it's not really required but I just made a blank file anyways to satisfy the requirement.    Is this correct?    What should I be doing if '/etc/initrd-release' doesn't exist?

Can someone please update the README explaining the proper way to fix a missing '/etc/initrd-release' file and whether or not it's actually required.

**Comment by Andrei-Pozolotin** [comment]
1. `/etc/initrd-release` is a marker file required by `systemd` inside `ramfs`
https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

2. yes, providing empty `/etc/initrd-release` inside the `ramfs` is a valid workaround

3. one way to provide `/etc/initrd-release` is via 
https://github.com/random-archer/mkinitcpio-systemd-tool#provisioning-questions-and-answers
```
is there a way to create empty folder or file?

for empty dir, use InitrdPath=/path/target-dir/ create=yes note trailing SLASH
for empty file, use InitrdPath=/path/target-file create=yes note NO trailing slash
```
