### ISSUE TITLE
[Question]  Where do I put my mount options?

### ISSUE THREAD

**Issue by ShapeShifter499** [random-archer/mkinitcpio-systemd-tool#14]
It's a bit hard for me to follow the whole thing going on here.  Should I be editing '/etc/mkinitcpio.d/fstab' and '/etc/mkinitcpio.d/crypttab'   or will it pickup on edits to the normal '/etc/fstab' and '/etc/crypttab' locations?

**Comment by ShapeShifter499** [comment]
I'm guessing anything that I want to decrypt goes in '/etc/mkinitcpio.d/fstab' and '/etc/mkinitcpio.d/crypttab'     otherwise I'd use the standard locations '/etc/fstab' and '/etc/crypttab'        I'm not sure though.

**Comment by Andrei-Pozolotin** [comment]
these files
https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/crypttab
https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/fstab

are embedded into initrd image via
https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/initrd-cryptsetup.service#L33

perhaps more experimentation will help comprehension :-)
https://harpers.org/blog/2007/12/blake-on-knowledge-through-experience/
