### ISSUE TITLE
initrd-cryptsetup luks2 incompatible

### ISSUE THREAD

**Issue by vvl-rulez** [random-archer/mkinitcpio-systemd-tool#19]
If disk have luks2 format, hook asks password (secret> ... ), but exit with error 
```
libgcc_s.so.1 must be installed for pthread_cancel to work
```
Error describbed in this [topic](https://bugs.archlinux.org/task/56771), but for another hook.

**Comment by Andrei-Pozolotin** [comment]
try adding library dependency config stanza to the service:
https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/initrd-cryptsetup.service
```
# luks2 disk format work around, see #19
InitrdBinary=/usr/lib/libgcc_s.so.1 optional=yes
```

**Comment by Andrei-Pozolotin** [comment]
assume resolved
