### ISSUE TITLE
TinySSH instead of (as an optional alternative to) Dropbear?

### ISSUE THREAD

**Issue by ArchangeGabriel** [random-archer/mkinitcpio-systemd-tool#22]
I’m using TinySSH instead of Dropbear because of its much more tiny codebase and supports for Ed25519 keys. Could it be added as an optional replacement to Dropbear? The later only supports RSA keys AFAIK and has a way bigger footprint.

**Comment by Andrei-Pozolotin** [comment]
resolved by https://github.com/random-archer/mkinitcpio-systemd-tool/releases/tag/v17
