### ISSUE TITLE
Improve README so it's clear how to add custom binaries or services

### ISSUE THREAD

**Issue by irreleph4nt** [random-archer/mkinitcpio-systemd-tool#24]
Hi,

Setting up systemd and systemd-tool hooks took quite some time already because of the lack of useful or understandable documentation (English!). Adding a custom service that uses systemd-tool is basically impossible due to very lacking documentation (README / wiki). This can be a great tool, but only if other devs actually understand how to use it.

In my case, I am looking to add bluetooth connectivity to initramfs.

Kind regards.

**Comment by Andrei-Pozolotin** [comment]
Sorry no time for extra docs now. Please create "bluetooth" wiki page after you succeed.
