### ISSUE TITLE
Unit drop-in files are not honored (at least for dropbear)

### ISSUE THREAD

**Issue by julianbrost** [random-archer/mkinitcpio-systemd-tool#3]
I tried to make dropbear listen on a different port by placing a file with the following contents at `/etc/systemd/system/initrd-dropbear.service.d/override.conf`:

```
[Service]
ExecStart=/bin/dropbear -s -j -k -m -F -I ${IDLE_TIME} -p 1234
```

It is not even copied to the initramfs and thus dropbear will still listen on port 22.

Also, I would prefer to have a better way to configure the listening port.

**Comment by Andrei-Pozolotin** [comment]
right, `initrd-xxx.service.d` are not copied now, please feel free to send pr

**Comment by julianbrost** [comment]
I'll try to. Can you explain to me how https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/mkinitcpio-install.sh#L75 gets its input? Looks like one wants to also iterate over the drop-in files there.

Also I see two possible ways of implementing this:

1. Manually look for the drop-in files and copy them
2. Use `systemctl cat $unit`, which will automatically add the drop-in files. This looks somewhat nicer to me, but probably requires some bigger changes in `add_systemd_unit_X`.

**Comment by Andrei-Pozolotin** [comment]
assume resolved

**Comment by julianbrost** [comment]
Were there any changes to the code to implement this?

**Comment by Andrei-Pozolotin** [comment]
no
