### ISSUE TITLE
ci: repo install

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [random-archer/mkinitcpio-systemd-tool#40]
replace `manual-setup.sh` with better approximation to `pacman -S`

**Comment by Andrei-Pozolotin** [comment]
@dvzrv David:

I think you are an expert on this, so please help:

PROBLEM:
* there is a need to install code from git repo inside azure ci
* so in order to avoid heavy download of `base-devel` during ci builds:
* the following hack is used, to emulate `pacman -S mkinitcpio-systemd-tool`
[tool/module/manual-setup.sh](https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/tool/module/manual-setup.sh)

QUESTION:
* can you recommend still "lightweight", but "higher fidelity" way of doing that install?

**Comment by Andrei-Pozolotin** [comment]
@dvzrv David: please respond

**Comment by dvzrv** [comment]
Hey! Sorry, I got sidetracked by other things.

I'm not super in the picture in regards to the test framework that you've established tbh.
The `base-devel` group is ~ 225Mb in size (24 packages), so in theory this really is no problem.

It really depends on what you're striving for: If you want to establish proper reproducibility you will want to
* build a qemu image from scratch every time
* install mkinitcpio-systemd-tool via `make PREFIX=/usr install` into it

This would be not much different from how we're building the package using devtools: It creates a pristine nspawn container with all required dependencies and then creates the package in there. Afterwards the package is installed into the same environment to check for consistency.

You're going one step further (without building a package) and reboot to make sure that remote console is accessible, IIUC.

**Comment by Andrei-Pozolotin** [comment]
> Hey! Sorry, I got sidetracked by other things.

1. sure, I understand, no problem

2. thank you for your note, it helps:
* I will use `base-devel`, and then 
* make sure the image is cached by azure
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
