### ISSUE TITLE
Bridge creation in initramfs?

### ISSUE THREAD

**Issue by adam900710** [random-archer/mkinitcpio-systemd-tool#76]
Hi,

It looks like the `systemd-tool` hook only reads the file `initrd-network.network`, but not the full `*.netdev` `*.network`, which makes it pretty hard to create bridge device.

Is it possible to create bridges at initramfs? Or is there any special config grammar that I can put all the bridge setup into the same file?

**Comment by Andrei-Pozolotin** [comment]
assume resolved

**Comment by adam900710** [comment]
Yep, resolved.

In fact, it turns out that re-building the network interface after network-manager or whatever the tool is completely fine.

Since the main purpose for the network in initramfs is for LUKS decryption, it doesn't really matter any more.
