### ISSUE TITLE
Wireguard tunnel using initrd-network.service

### ISSUE THREAD

**Issue by zhulik** [random-archer/mkinitcpio-systemd-tool#77]
Hello!

Thanks for the awesome project!

I have a small question:
Is it possible to setup a wireguard tunnel from initrd using `initrd-network.service` ?

If it is, than may I have some hints on how to achieve it?
It it's not, then I'd like to know what exactly is missing, maybe I can help with implementation.

Thank you!

**Comment by zhulik** [comment]
Thanks to @Andrei-Pozolotin, I used https://github.com/random-archer/mkinitcpio-systemd-tool/issues/76#issuecomment-678657756 as an example, the solution is very easy

`/etc/systemd/system/initrd-network.service.d/override.conf`:
```
[X-SystemdTool]
InitrdCall=add_module wireguard
InitrdPath=/etc/systemd/network/99-client.netdev source=/etc/systemd/network/99-client.netdev
InitrdPath=/etc/systemd/network/99-client.network source=/etc/systemd/network/99-client.network
```

Where `/etc/systemd/network/99-client.netdev` and `/etc/systemd/network/99-client.network` are tunnel config files described in the [wiki](https://wiki.archlinux.org/index.php/WireGuard#systemd-networkd)

**Comment by Andrei-Pozolotin** [comment]
@zhulik Gleb: please add a wiki page here with a bit more complete instructions for others to re-use
