### ISSUE TITLE
How to disable timeout?

### ISSUE THREAD

**Issue by hansWURSCHT10000** [random-archer/mkinitcpio-systemd-tool#9]
Hello, I just installed your tool to decrypt my root partition via SSH. 
It works fine but only for 90 seconds. Then an emergency shell gets started and I can no longer connect via SSH.  
Where can I disable this timeout?

Message:
`A start job is running for dev-mapper-main\x2droot.device (10s / 1min 30s)`

After Timeout:
```
[DEPEND] Dependency failed for Initrd Root Device.
[DEPEND] Dependency failed for File System Check on /dev/mapper/main-root.
[...]
```

then all services stop and the emergency shell gets started.

I enabled these services:
```
systemctl enable initrd-cryptsetup.path
systemctl enable initrd-network.service
systemctl enable initrd-dropbear.service
systemctl enable initrd-shell.service

```

```
$ lsblk
NAME            MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda               8:0    0 931,5G  0 disk  
├─sda1            8:1    0   500M  0 part  /boot
└─sda2            8:2    0   931G  0 part  
  └─main        254:0    0   931G  0 crypt 
    ├─main-swap 254:1    0     8G  0 lvm   [SWAP]
    └─main-root 254:2    0   923G  0 lvm   /
```

**Comment by Andrei-Pozolotin** [comment]
try
https://github.com/random-archer/mkinitcpio-systemd-tool/wiki
https://github.com/random-archer/mkinitcpio-systemd-tool/issues/2

**Comment by Andrei-Pozolotin** [comment]
assume resolved
