### ISSUE TITLE
[tinyssh-convert] command usage changed

### ISSUE THREAD

**Issue by duffydack** [random-archer/mkinitcpio-systemd-tool#90]
Since the tinyssh package updated, it now includes the tinyssh-convert binary, where previous I had to use the separate tinyssh-convert pkg for use with this hook.  The command used in `/usr/lib/mkinitcpio-systemd-tool/initrd-build.sh` script is...

`tinyssh-convert -f /etc/ssh/ssh_host_ed25519_key -d $keydir`

which fails due to the command usage now being `tinyssh-convert out-tinysshkeydir < in-opensshfile`.
This still fails however as the $keydir exists already, and will only succeed when it doesn't.  
So trying again without $keydir existing, it succeeds.  However, it fails when ran again, because keydir exists. 
`tinyssh-convert: fatal: out-tinysshkeydir exist`

**Comment by ArchangeGabriel** [comment]
See #89.

**Comment by duffydack** [comment]
Didn't see it.  Good point about key doesn't need to convert everytime, so I'll just comment out the converting bit, and do it manually if it ever needs doing again.

**Comment by dvzrv** [comment]
Fixed with #89
